"""Топ 50 компании в света по пазарна капитализация (companiesmarketcap.com, септември 2026).

Списъкът се променя с времето; обновявай го ръчно от време на време.
Тикерите са във формат на Yahoo Finance.
"""

TOP50 = [
    ("NVDA", "NVIDIA", "САЩ"),
    ("AAPL", "Apple", "САЩ"),
    ("GOOGL", "Alphabet (Google)", "САЩ"),
    ("MSFT", "Microsoft", "САЩ"),
    ("AMZN", "Amazon", "САЩ"),
    ("TSM", "TSMC", "Тайван"),
    ("META", "Meta Platforms", "САЩ"),
    ("SPCX", "SpaceX", "САЩ"),
    ("AVGO", "Broadcom", "САЩ"),
    ("2222.SR", "Saudi Aramco", "Саудитска Арабия"),
    ("TSLA", "Tesla", "САЩ"),
    ("005930.KS", "Samsung", "Южна Корея"),
    ("MU", "Micron Technology", "САЩ"),
    ("BRK-B", "Berkshire Hathaway", "САЩ"),
    ("LLY", "Eli Lilly", "САЩ"),
    ("AMD", "AMD", "САЩ"),
    ("000660.KS", "SK Hynix", "Южна Корея"),
    ("JPM", "JPMorgan Chase", "САЩ"),
    ("WMT", "Walmart", "САЩ"),
    ("V", "Visa", "САЩ"),
    ("INTC", "Intel", "САЩ"),
    ("XOM", "Exxon Mobil", "САЩ"),
    ("ASML", "ASML", "Нидерландия"),
    ("JNJ", "Johnson & Johnson", "САЩ"),
    ("688825.SS", "CXMT", "Китай"),
    ("TCEHY", "Tencent", "Китай"),
    ("MA", "Mastercard", "САЩ"),
    ("ABBV", "AbbVie", "САЩ"),
    ("PLTR", "Palantir", "САЩ"),
    ("601939.SS", "China Construction Bank", "Китай"),
    ("ORCL", "Oracle", "САЩ"),
    ("CSCO", "Cisco", "САЩ"),
    ("CVX", "Chevron", "САЩ"),
    ("COST", "Costco", "САЩ"),
    ("BAC", "Bank of America", "САЩ"),
    ("LRCX", "Lam Research", "САЩ"),
    ("KO", "Coca-Cola", "САЩ"),
    ("AMAT", "Applied Materials", "САЩ"),
    ("CAT", "Caterpillar", "САЩ"),
    ("MRK", "Merck", "САЩ"),
    ("ROG.SW", "Roche", "Швейцария"),
    ("601288.SS", "Agricultural Bank of China", "Китай"),
    ("HSBC", "HSBC", "Великобритания"),
    ("1398.HK", "ICBC", "Китай"),
    ("DELL", "Dell", "САЩ"),
    ("PG", "Procter & Gamble", "САЩ"),
    ("UNH", "UnitedHealth", "САЩ"),
    ("GE", "General Electric", "САЩ"),
    ("ARM", "Arm Holdings", "Великобритания"),
    ("PANW", "Palo Alto Networks", "САЩ"),
]
